### ISSUE TITLE
继承自BaseDialog后，自定义布局里有个EditText，输入法不能把对话框重新弹到居中位置

### ISSUE THREAD

**Issue by wordplat** [H07000223/FlycoDialog_Master#10]

**Comment by wordplat** [comment]
![](http://i4.tietuku.com/407fe03ed7d4042c.jpg)
![](http://i4.tietuku.com/fda79b9a6a9ad548.jpg)

**Comment by H07000223** [comment]
在自定义的Dialog中构造方法调用super(context,true)方法.这个有个坏处是有些动画显示不太完美.
```java
public CustomDialog(Context context) {
    super(context,true);
}
```

**Comment by wordplat** [comment]
调用了super(context,true)方法~它成功了！
![](http://i4.tietuku.com/ccbf7e273d693d31.jpg)

**Comment by xinnuo** [comment]
thank you!
