### ISSUE TITLE
library is missing

### ISSUE THREAD

**Issue by abdulrahmanmajeed** [H07000223/FlycoDialog_Master#11]
import butterknife.Bind;
import butterknife.ButterKnife;
import butterknife.OnClick; 

above mentioned libraries are missing while i already setup gradle with 
compile 'com.flyco.dialog:FlycoDialog_Lib:1.2.6@aar'
    compile 'com.nineoldandroids:library:2.4.0'

**Comment by H07000223** [comment]
Sorry I don't know what causes it. Maybe you can restart AS.
