### ISSUE TITLE
你好，在实际使用过程中发现一个问题，点击对话框里面任何位置，对话框都会dismiss？

### ISSUE THREAD

**Issue by soyoungboy** [H07000223/FlycoDialog_Master#14]
你好，在实际使用过程中发现一个问题，点击对话框里面任何位置，对话框都会dismiss，我想控制用户不点击按钮，对话框就不消失，但是没有找到对应的方法。

**Comment by H07000223** [comment]
额~好像是个bug,下个版本修复吧.暂时的话你要是允许对话框以外也不能点击的话,可以使用dialog.setCanceledOnTouchOutside(false);

**Comment by soyoungboy** [comment]
不是对话框以外，是对话框内部，但不是按钮的地方（sorry,没表述清楚）

**Comment by H07000223** [comment]
知道哇~暂时是个bug~但是dialog.setCanceledOnTouchOutside(false);我覆写了,可以让内部也不可点~
但是外部也是了,等我修复,下个版本,很快的~😂

**Comment by soyoungboy** [comment]
![image](https://cloud.githubusercontent.com/assets/8855422/14884142/6402ac32-0d75-11e6-9fcc-03a32a018001.png)
期待中

**Comment by H07000223** [comment]
在最新的1.2.8里面fix了~
