### ISSUE TITLE
Custom View

### ISSUE THREAD

**Issue by abdulrahmanmajeed** [H07000223/FlycoDialog_Master#18]
you mean to sat there is no way to use custom view ?? right ??

**Comment by H07000223** [comment]
[qucik-customize-dialog](https://github.com/H07000223/FlycoDialog_Master#qucik-customize-dialog)

**Comment by H07000223** [comment]
[qucik-customize-dialog](https://github.com/H07000223/FlycoDialog_Master#qucik-customize-dialog)
