### ISSUE TITLE
关于popupwindow的问题

### ISSUE THREAD

**Issue by smallstrong0** [H07000223/FlycoDialog_Master#19]
自定义一个popupwindow，然后出现一个问题。就是点击外部pop不消失，确定是设置了setCanceledOnTouchOutside 但是并么有用

**Comment by H07000223** [comment]
可以的啊~我在库Demo中SimpleCustomPop的构造方法设置了
setCanceledOnTouchOutside(false);可以的啊~
你用最新的库再试试~

**Comment by alexandre-g** [comment]
Hi, nice library! I believe I'm facing the same issue.. trying to find why it doesn't dismiss but with no success so far. There are no `setCanceledOnTouchOutside(false)` to be found, tried setting to true explicitly as well but still no go..

**Comment by H07000223** [comment]
BasePopup.setCanceledOnTouchOutside(boolean cancel)
