### ISSUE TITLE
弹出的dialog 点击空白区域 怎么能不消失对话框 

### ISSUE THREAD

**Issue by youngchen1987** [H07000223/FlycoDialog_Master#20]
弹出的dialog 点击空白区域 怎么能不消失对话框   我网上找了一些例子 都不管用  求教啊

**Comment by H07000223** [comment]
setCanceledOnTouchOutside(false);

**Comment by youngchen1987** [comment]
不管用的 增加了这个仍然可以点击dialog 仍然关闭

![image](https://cloud.githubusercontent.com/assets/11566474/16679188/22635c2e-4518-11e6-8496-3dd49350f27e.png)

**Comment by H07000223** [comment]
使用的是不是最新库嘛，如果是的话不应该啊
你尝试在dialog new之后，加dialog.setCanceledOnTouchOutside(false);

**Comment by youngchen1987** [comment]
已经解决  重写下oncreate方法就可以了
![image](https://cloud.githubusercontent.com/assets/11566474/16707066/ea4a0548-45f5-11e6-8d0a-0a2811286c3a.png)
