### ISSUE TITLE
有没有flycodialog的qq群呢？

### ISSUE THREAD

**Issue by youngchen1987** [H07000223/FlycoDialog_Master#21]
有没有flycodialog的qq群呢？

**Comment by H07000223** [comment]
没有~

**Comment by youngchen1987** [comment]
我刚才咨询的弹框 点击空白 按照你的方法  不管用  求解

**Comment by youngchen1987** [comment]
![image](https://cloud.githubusercontent.com/assets/11566474/16680233/c6fac9c8-451f-11e6-9b47-ca6e8d8b4879.png)

**Comment by H07000223** [comment]
你用的库版本号~

**Comment by youngchen1987** [comment]
![image](https://cloud.githubusercontent.com/assets/11566474/16705216/905fd34a-45b5-11e6-8258-bb772bb657fe.png)

**Comment by H07000223** [comment]
Eclipse版本jar包不更新维护的，你可以把代码拷贝进去使用
