### ISSUE TITLE
屏幕转动后直接dismiss了，能否保持打开状态

### ISSUE THREAD

**Issue by ysmintor** [H07000223/FlycoDialog_Master#24]
手动在savebundle里，不知道这个项目是否可以增加这个功能？

**Comment by owenmike** [comment]
可以创建一个继承于 `DialogFragment` 的类，然后重写它的 `onCreateDialog()` 方法，在方法里创建 FlycoDialog

**Comment by ysmintor** [comment]
@okadaNana 是的，感觉现在官方更建议使用DialogFragment，生命周期好管理。
