### ISSUE TITLE
popup点击以外区域无法dismiss求解！

### ISSUE THREAD

**Issue by ynhenggg** [H07000223/FlycoDialog_Master#25]
Dear H07000223,
     库很好用，在使用dialog过程中简化操作，也非常易用、漂亮。
现在有个需要用popup的需求，于是就使用了你的这个BasePopup，
试了很多遍却发现不能像dialog一样，在点击内容区域外部取消操作，
设置了setCanceledOnTouchOutside(true)之后也不起作用，
目前已在项目中...急求解....非常感谢您的开源.

**Comment by H07000223** [comment]
这个bug修复了，使用1.3.3版本

**Comment by ynhenggg** [comment]
非常感谢，那我关闭这个issues了
