### ISSUE TITLE
Can't change button colors

### ISSUE THREAD

**Issue by silviahisham** [H07000223/FlycoDialog_Master#3]
I tried using    dialog.btnTextColor(Color.parseColor("#ff0000")) but no use, buttons are always blue.

**Comment by H07000223** [comment]
I want to know the exact dialog to find the bug, NormalDialog or MaterialDialog or others?

**Comment by silviahisham** [comment]
Material dialog

**Comment by H07000223** [comment]
Hope the method  comments in BaseAlertDialog blew will help you. If not,I will try myself to fix it.
 /**
     * set btn textcolor
     * btnTextColors size 1, middle
     * btnTextColors size 2, left right
     * btnTextColors size 3, left right middle
     */
    public T btnTextColor(int... btnTextColors)

**Comment by silviahisham** [comment]
That's exactly what i used actually, don't know why it's not changing its color.

**Comment by H07000223** [comment]
I try it in the sample. It is ok. Show me you code about using dialog. Or you can try it in github sample first.

**Comment by silviahisham** [comment]
It worked! thanks a lot for your help, the problem was not setting .btnNum(2)
