### ISSUE TITLE
用了NormalListDialogNoTitle，每个item都是从左边飘进来的，不要这个动画效果怎么写

### ISSUE THREAD

**Issue by wohao** [H07000223/FlycoDialog_Master#32]

**Comment by H07000223** [comment]
设置showAnim(null)

**Comment by wohao** [comment]
额，设置了showAnim(null), 可是item里面的文字还是从左边飘进来的，我不要这个文字的效果要怎么做啊

**Comment by H07000223** [comment]
layoutAnimation(null)

**Comment by wohao** [comment]
哈哈，谢谢

**Comment by wohao** [comment]
dialog的半透明黑色背景可以设置吗？我用dialog.getWindow().setBackgroundDrawable(); 没有效果。。

**Comment by H07000223** [comment]
自定义dialog的话,可以尝试用一个全屏的布局实现
