### ISSUE TITLE
WindowManager: android.view.WindowLeaked

### ISSUE THREAD

**Issue by PiPiCaptain** [H07000223/FlycoDialog_Master#34]
WindowManager: android.view.WindowLeaked: Activity xxx has leaked window com.android.internal.policy.impl.PhoneWindow

出现这样的Error，如何解决

**Comment by H07000223** [comment]
这不是库的锅，正常对话框都有~
最好能标记activity销毁~否做的话try catch 之~😂

**Comment by PiPiCaptain** [comment]
@H07000223 好的，感谢。

**Comment by PiPiCaptain** [comment]
@H07000223 再次确认了一下这个问题，加入了进入、退出动画，就会报这个错误。我觉得应该是退出动画还没完成，Activity已经finish了。

**Comment by H07000223** [comment]
退出~在onDestory调用superDismiss，这个方法没动画
