### ISSUE TITLE
Qucik Customize Dialog doesn't work

### ISSUE THREAD

**Issue by aresares** [H07000223/FlycoDialog_Master#36]
Hi I'm trying to make a custom dialog like in the example "**Qucik Customize Dialog**" but i give me some errors here
```
tv_cancel = ViewFindUtils.find(inflate, R.id.tv_cancel);
tv_exit = ViewFindUtils.find(inflate, R.id.tv_exit);
```

it seems that ViewFindUtils doesn't exist. I tried to use LayoutInflate with no success

**Comment by H07000223** [comment]
use findById instead
