### ISSUE TITLE
双击之后出现2个对话框，只能关闭一个

### ISSUE THREAD

**Issue by liericiyan** [H07000223/FlycoDialog_Master#4]
双击之后出现2个对话框，只能关闭一个，最后一个点击button没有反应，点击返回键也没有反应，只能强制干掉app。请问有没有好的解决方案？谢谢，这个出现的概率不高，在LG g3，4.4.2版本上测试的

**Comment by H07000223** [comment]
可以尝试点击通过判断dialog!=null&&dialog.isShowing,做处理~

**Comment by liericiyan** [comment]
谢谢，我点击的时候每次都new 了新对象，导致双击之后弹出2个对话框，后来我把初始化操作写作了onCreate里，click事件只写show方法，完美解决这个问题

**Comment by H07000223** [comment]
没事~解决就好~😁
