### ISSUE TITLE
建议升级使用DialogFragment

### ISSUE THREAD

**Issue by ysmintor** [H07000223/FlycoDialog_Master#43]
DialogFragment是Android主推荐使用方式，可以有效管理生命周期，也解决了旋转Dialog没有创建等，对话框输入键盘弹出Dialog上移等处理。一般MD风格用AlertDialog就行，但国内很大Android还是仿IOS 对话框，使用上希望FlycoDialog能够以DialogFragment来实现，对于自定义view可以如AlertDialog那样方便使用addView()来添加内容区域。

在[CodePath](http://guides.codepath.com/android/Using-DialogFragment#usage)  中有

> DialogFragment is now the canonical way to display overlays; using Dialog directly is considered bad practice.

**Comment by yangchong211** [comment]
弹窗Toast，SnackBar，Dialog，DialogFragment，PopupWindow都包含，功能强大。https://github.com/yangchong211/YCDialog

**Comment by ysmintor** [comment]
@yangchong211 很强！去年的 issue，今年收到了回复。只是目前自己重心放在学习其它技术了。
