### ISSUE TITLE
点击窗外关闭窗口

### ISSUE THREAD

**Issue by KobeKomi** [H07000223/FlycoDialog_Master#5]
setCanceledOnTouchOutside(false)无效

**Comment by H07000223** [comment]
自定义dialog的话~写到setUiBeforShow就可以了~

**Comment by KobeKomi** [comment]
OK!

**Comment by H07000223** [comment]
嗯,谢谢你的建议,不过以回调接口的形式,我可能换种方式修复这个bug~导致这个原因主要是因为我在BaseDialog中onCreate方法setCanceledOnTouchOutside(true);
