### ISSUE TITLE
Unable to set cancel text in ActionSheetDialog

### ISSUE THREAD

**Issue by Awais-Ali** [H07000223/FlycoDialog_Master#6]
while using ActionSheetDialog you can set content menu items and can't able to set text for cancel ,its shows me in native language of the repo's developer.please suggest me the workable solution.

**Comment by H07000223** [comment]
Already added in version 1.1.8.

**Comment by Awais-Ali** [comment]
I didn't find any setter property for it,please can you show me here so far

**Comment by H07000223** [comment]
The lib updates,  look up the lastest version 1.1.8
