### ISSUE TITLE
NormalDialogCustomAttr has default color  

### ISSUE THREAD

**Issue by Awais-Ali** [H07000223/FlycoDialog_Master#7]
What i am currently trying to achieve  is white as a background color  but i cant way out

**Comment by H07000223** [comment]
I try what you say and it's ok.
```java
  final NormalDialog dialog = new NormalDialog(mContext);
  dialog.isTitleShow(false)//
            .bgColor(Color.parseColor("#ffffff"))
            ...
            .show();
```
More details , you can see the demo. If it still dosen't work, then please show me your code. I will try my best to find what's wrong.

**Comment by Awais-Ali** [comment]
Thanks Flyco!
