### ISSUE TITLE
BubblePopup为什么只响应一个TextView的点击事件

### ISSUE THREAD

**Issue by tikkat3** [H07000223/FlycoDialog_Master#8]
我的代码如下：

View inflate = View.inflate(getContext(), R.layout.widget_main_subject, null);
                inflate.findViewById(R.id.main_one).setOnClickListener(this);
                inflate.findViewById(R.id.main_two).setOnClickListener(this);
             BubblePopup bubblePopup = new BubblePopup(getContext(), inflate);
                bubblePopup.anchorView(mTitle)
                        .show();

为什么只有第一个textview的事件被响应了？

**Comment by H07000223** [comment]
的确,有这个问题.我暂时没时间改~这个BubblePopup本意是只用纯来展示的,后期的话,应该会抽出个
BaseBubblePopup用来继承,类似BaseDialog一样的操作.

目前的话,你可以尝试继承BubblePopup,将监听事件写在setUiBeforShow() 

```java
public class CustomBubblePopup extends BubblePopup<CustomBubblePopup>{
    public BubblePopup(Context context) {
        super(context,View.inflate(getContext(), R.layout.widget_main_subject, null));
    }

    @Override
    public void setUiBeforShow() {
       super.setUiBeforShow();
       mWrappedView.findViewById(R.id.main_one).setOnClickListener(this);
       mWrappedView.findViewById(R.id.main_two).setOnClickListener(this);
    }

}
```

**Comment by H07000223** [comment]
已经fix~使用最新版本v1.2.6~

**Comment by tikkat3** [comment]
Good Work !
