### ISSUE TITLE
contentTextColor(Color.parseColor("#000000"))// not set this colour

### ISSUE THREAD

**Issue by Awais-Ali** [H07000223/FlycoDialog_Master#9]
In Normal Dialog ,contentTextColor(Color.parseColor("#000000"))// not set this colour,and text is  not visible on the dialog.

**Comment by H07000223** [comment]
I don't know what cause your problem. For Normal Dialog, it has default value. So if you don't set, it will use default color. Maybe you can show me the code, I will try my best to help you find out the problem.
```java
        /** default value*/
        mTitleTextColor = Color.parseColor("#61AEDC");
        mTitleTextSize = 22f;
        mContentTextColor = Color.parseColor("#383838");
        mContentTextSize = 17f;
        mLeftBtnTextColor = Color.parseColor("#8a000000");
        mRightBtnTextColor = Color.parseColor("#8a000000");
        mMiddleBtnTextColor = Color.parseColor("#8a000000");
        /** default value*/
```

**Comment by Awais-Ali** [comment]
This is code Snippet,i am trying to set content color black,but its could not be handle by this.
 
 dialog.isTitleShow(false)//
                .bgColor(getResources().getColor(R.color.colorLightgray))//
                .cornerRadius(5)//
                .content(content)//
                .contentGravity(Gravity.CENTER)//
                .contentTextColor(Color.parseColor("#000000"))//
                .dividerColor(getResources().getColor(R.color.colorPrimary))//
                .btnTextSize(15.5f, 15.5f)//
                        .btnTextColor(getResources().getColor(R.color.colorPrimaryDark)
                                , getResources().getColor(R.color.colorPrimaryDark))//
                .btnPressColor(getResources().getColor(R.color.colorDarkgray))//
                .widthScale(0.85f)//
                .showAnim(new BounceLeftEnter())//
                .dismissAnim(new SlideRightExit())//
                .show();
Why default colour are used ,when i put my own.

**Comment by H07000223** [comment]
I have tried and It's ok in my demo with the lastest lib.
```groovy
dependencies{
     compile 'com.flyco.dialog:FlycoDialog_Lib:1.2.2@aar'
     compile 'com.flyco.animation:FlycoAnimation_Lib:1.0.0@aar'
     compile 'com.nineoldandroids:library:2.4.0'
}
```

```Java
 private void NormalDialogCustomAttr() {
        final NormalDialog dialog = new NormalDialog(mContext);
        dialog.isTitleShow(false)//
                .bgColor(Color.parseColor("#383838"))//
                .cornerRadius(5)//
                .content("是否确定退出程序?")//
                .contentGravity(Gravity.CENTER)//
                .contentTextColor(Color.CYAN)//
                .dividerColor(Color.parseColor("#222222"))//
                .btnTextSize(15.5f, 15.5f)//
                .btnTextColor(Color.parseColor("#ffffff"), Color.parseColor("#ffffff"))//
                .btnPressColor(Color.parseColor("#2B2B2B"))//
                .widthScale(0.85f)//
                .showAnim(mBasIn)//
                .dismissAnim(mBasOut)//
                .show();
}
```

**Comment by Awais-Ali** [comment]
replace my color with your color in contentTextColor.

**Comment by H07000223** [comment]
I have tried "#000000", also ok.
![image](https://cloud.githubusercontent.com/assets/3666423/12141899/a926a7ac-b4ae-11e5-98f9-1d993fba6537.png)

**Comment by Awais-Ali** [comment]
Thanks ...but i can't way out i have tried the Same...Anyways check it again...
Thanks Flyco

**Comment by H07000223** [comment]
Unstall your apk, then clean project and run again.
If still, since UI is not complex , you can try cutomize dialog by extending BaseDialog.

**Comment by Awais-Ali** [comment]
Yes ,Man ,i had updated BaseAlertDialog Class,Now its Perfect,thanks for assistance.
